In [1]:
import pandas as pd
import os

In [2]:
#Create path 
path= '/Users/shantamaraj/Desktop/Basketball Analytics/Processed Data'

In [3]:
# Import Data
df= pd.read_csv(os.path.join(path, 'nba_updated_coordinates.csv'))

df.head()

,regular_season_index,season_start,season_end,season_type,player_id,rank,player,team_id,team,games_played,...,personal_fouls,total_points,assist_to_turnover_ratio,steal_to_turnover_ratio,playoff_index,country,team_full,state,latitude,longitude
0,0.0,2012,2013,Regular,201142,1,Kevin Durant,1610612760,OKC,81,...,143,2280,1.34,0.41,NaN,United States of America,Oklahoma City Thunder,Oklahoma,35.4634,-97.5151
1,1.0,2012,2013,Regular,977,2,Kobe Bryant,1610612747,LAL,78,...,173,2133,1.63,0.37,NaN,United States of America,Los Angeles Lakers,California,34.0430,-118.2673
2,2.0,2012,2013,Regular,2544,3,LeBron James,1610612748,MIA,76,...,110,2036,2.44,0.57,NaN,United States of America,Miami Heat,Florida,25.7814,-80.1870
3,3.0,2012,2013,Regular,201935,4,James Harden,1610612745,HOU,78,...,178,2023,1.54,0.48,NaN,United States of America,Houston Rockets,Texas,29.7508,-95.3621
4,4.0,2012,2013,Regular,2546,5,Carmelo Anthony,1610612752,NYK,67,...,205,1920,0.98,0.30,NaN,United States of America,New York Knicks,New York,40.7505,-73.9934

In [4]:
df.shape

(8046, 37)

In [5]:
df.columns

Index(['regular_season_index', 'season_start', 'season_end', 'season_type',
       'player_id', 'rank', 'player', 'team_id', 'team', 'games_played',
       'minutes_played', 'field_goals_made', 'field_goals_attempted',
       'field_goal_percentage', '3_point_feild_goals_made',
       '3_point_feild_goals_attempted', '3_point_feild_goal_percentage',
       'free_throws_made', 'free_throws_attempted', 'free_throw_percentage',
       'offensive_rebounds', 'defensive_rebounds', 'rebounds', 'assists',
       'steals', 'blocks', 'turnovers', 'personal_fouls', 'total_points',
       'assist_to_turnover_ratio', 'steal_to_turnover_ratio', 'playoff_index',
       'country', 'team_full', 'state', 'latitude', 'longitude'],
      dtype='object')

In [7]:
#Drop unnecessary columns for the 3-point analysis
df.drop([
    'regular_season_index',
    'season_type',
    'player_id',
    'rank',
    'team_id',
    'field_goals_made',
    'field_goals_attempted',
    'field_goal_percentage',
    'free_throws_made',
    'free_throws_attempted',
    'free_throw_percentage',
    'offensive_rebounds',
    'defensive_rebounds',
    'rebounds',
    'steals',
    'blocks',
    'personal_fouls',
    'assist_to_turnover_ratio',
    'steal_to_turnover_ratio',
    'playoff_index',
    'latitude',
    'longitude',], axis=1)

,season_start,season_end,player,team,games_played,minutes_played,3_point_feild_goals_made,3_point_feild_goals_attempted,3_point_feild_goal_percentage,assists,turnovers,total_points,country,team_full,state
0,2012,2013,Kevin Durant,OKC,81,3119,139,334,0.416,374,280,2280,United States of America,Oklahoma City Thunder,Oklahoma
1,2012,2013,Kobe Bryant,LAL,78,3013,132,407,0.324,469,287,2133,United States of America,Los Angeles Lakers,California
2,2012,2013,LeBron James,MIA,76,2877,103,254,0.406,551,226,2036,United States of America,Miami Heat,Florida
3,2012,2013,James Harden,HOU,78,2985,179,486,0.368,455,295,2023,United States of America,Houston Rockets,Texas
4,2012,2013,Carmelo Anthony,NYK,67,2482,157,414,0.379,171,175,1920,United States of America,New York Knicks,New York
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8041,2023,2024,Olivier-Maxence Prosper,DAL,3,9,0,0,0.000,1,0,0,United States of America,Dallas Mavericks,Texas
8042,2023,2024,Orlando Robinson,MIA,1,2,0,1,0.000,1,0,0,United States of America,Miami Heat,Florida
8043,2023,2024,T.J. Warren,MIN,3,11,0,1,0.000,1,0,0,United States of America,Minnesota Timberwolves,Minnesota
8044,2023,2024,Thaddeus Young,PHX,1,4,0,0,0.000,0,0,0,United States of America,Phoenix Suns,Arizona
8045,2023,2024,Thanasis Antetokounmpo,MIL,2,5,0,0,0.000,0,0,0,United States of America,Milwaukee Bucks,Wisconsin

In [8]:
df.shape

(8046, 37)

In [9]:
df = df.drop([
    'regular_season_index', 'season_type', 'player_id', 'rank', 'team_id',
    'field_goals_made', 'field_goals_attempted', 'field_goal_percentage',
    'free_throws_made', 'free_throws_attempted', 'free_throw_percentage',
    'offensive_rebounds', 'defensive_rebounds', 'rebounds', 'steals',
    'blocks', 'personal_fouls', 'assist_to_turnover_ratio',
    'steal_to_turnover_ratio', 'playoff_index', 'latitude', 'longitude'
], axis=1)

In [10]:
df.shape

(8046, 15)

In [11]:
df.columns

Index(['season_start', 'season_end', 'player', 'team', 'games_played',
       'minutes_played', '3_point_feild_goals_made',
       '3_point_feild_goals_attempted', '3_point_feild_goal_percentage',
       'assists', 'turnovers', 'total_points', 'country', 'team_full',
       'state'],
      dtype='object')

In [12]:
#Rename columns

df.rename(columns={
    '3_point_feild_goals_made': '3PM',
    '3_point_feild_goals_attempted': '3PA',
    '3_point_feild_goal_percentage': '3P%',
    'team_full': 'team_fullname'}, inplace=True)

In [13]:
df.columns

Index(['season_start', 'season_end', 'player', 'team', 'games_played',
       'minutes_played', '3PM', '3PA', '3P%', 'assists', 'turnovers',
       'total_points', 'country', 'team_fullname', 'state'],
      dtype='object')

In [14]:
df.shape

(8046, 15)

In [15]:
#Save new df with only necessary columns for 3 point analysis 
df.to_csv(f"{path}/nba_3pt_data.csv", index=False)

### Dropping Unnecessary Columns for 3-Point Analysis

Since this project focuses specifically on the evolution of the 3-point shot in the NBA, 
I removed columns unrelated to shooting performance, such as free throws, rebounds, steals, and personal fouls. 
Keeping only relevant variables (3-point attempts, makes, accuracy, total points, assists, turnovers, and team information) 
streamlines the dataset for cleaner analysis and visualization.